name: full_stack_todo_dart
repository: https://github.com/saileshbro/full_stack_todo_dart.git

packages:
  - /**/pubspec.yaml

scripts:
  backend:dev:
    run: dart_frog dev
    exec:
      cuncurrency: 1
      fail-fast: true
    description: Starts the dev server for the backend
    select-package:
      scope: backend
      flutter: false

  generate:build:
    run: melos run build_runner:build --no-select
    description: Generate all files for all packages in this project.
    exec:
      concurrency: 5
      fail-fast: true

  build_runner:build:
    run: dart pub run build_runner build --delete-conflicting-outputs
    description: Build all generated files for Dart packages in this project.
    exec:
      concurrency: 1
      fail-fast: true
    select-package:
      depends-on: build_runner
      no-flutter: true

  test:dart:
    run: melos exec -c 1 --fail-fast -- "dart test"
    description: Run Dart tests for a specific package in this project.
    select-package:
      flutter: false
      dir-exists: test
