name: backend
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^0.3.2
  dart_jsonwebtoken: ^2.7.1
  data_source:
    path: ../data_source
  dotenv: ^4.1.0
  either_dart: ^0.3.0
  exceptions:
    path: ../exceptions
  failures:
    path: ../failures
  http: ^0.13.5
  models:
    path: ../models
  postgres: ^2.5.2
  repository:
    path: ../repository
  typedefs:
    path: ../typedefs

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.2
  very_good_analysis: ^3.1.0
