// Mocks generated by Mockito 5.4.0 from annotations
// in fullstack_todo/test/data/data_source/todo_remote_data_source/todos_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fullstack_todo/data/data_source/todos_http_client/todos_http_client.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTodo_0 extends _i1.SmartFake implements _i2.Todo {
  _FakeTodo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TodosHttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodosHttpClient extends _i1.Mock implements _i3.TodosHttpClient {
  MockTodosHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Todo>> getAllTodo() => (super.noSuchMethod(
        Invocation.method(
          #getAllTodo,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Todo>>.value(<_i2.Todo>[]),
      ) as _i4.Future<List<_i2.Todo>>);
  @override
  _i4.Future<_i2.Todo> getTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTodoById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #getTodoById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> createTodo(_i2.CreateTodoDto? todo) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTodo,
          [todo],
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #createTodo,
            [todo],
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<_i2.Todo> updateTodo(
    int? id,
    _i2.UpdateTodoDto? todo,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTodo,
          [
            id,
            todo,
          ],
        ),
        returnValue: _i4.Future<_i2.Todo>.value(_FakeTodo_0(
          this,
          Invocation.method(
            #updateTodo,
            [
              id,
              todo,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Todo>);
  @override
  _i4.Future<void> deleteTodoById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTodoById,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
