name: repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  data_source:
    path: ../data_source
  either_dart: ^0.3.0
  failures:
    path: ../failures
  models:
    path: ../models
  typedefs:
    path: ../typedefs

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.24.1
  very_good_analysis: ^4.0.0+1
